# -*- coding: utf-8 -*-
"""DS_In_Context_Presentation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19EaxK9ozS-rbC9eaoGFCnYzod4YvylYf

# Mount Colab to Your Google Drive
"""

from google.colab import drive
drive.mount('drive')

"""# Authenticate Google Account With Colab"""

from google.colab import auth
auth.authenticate_user()
print("Successfully authenticated...")

"""# Create BigQuery Client

This will enable the abilty to read, query, and write data directly from BigQuery.
"""

from google.cloud import bigquery
project_id = 'ds-in-context-presentation'
bq_client = bigquery.Client(project=project_id)

"""# Query Data from BigQuery

Data will be pulled via a SQL query and then transformed into a pandas dataframe that can be used for further analysis.
"""

query = '''
  SELECT
    ra.respondent_name,
    ra.movie_name,
    CASE
      WHEN ra.rating = "I've never seen this movie." THEN 0
      ELSE CAST(ra.rating as INT64) 
    END as rating,
    mo.category as movie_category,
    CAST(release_year as INT64) as movie_release_year,
    re.gender as respondent_gender,
    CAST(age as INT64) as respondent_age,
    re.profession as respondent_profession
  FROM `movie_survey.ratings` as ra
  LEFT JOIN `movie_survey.movies` as mo
  USING (movie_name)
  LEFT JOIN `movie_survey.respondents` as re
  USING (respondent_name)
'''

df = bq_client.query(query=query).to_dataframe()

df.head()

"""# Analyzing Query Results

**Example Question:** What is the average movie rating for those movies released after 1995?
"""

result = df[df['movie_release_year'] > 1995]
result = result.groupby(by='movie_name').mean()
result = result.reset_index()
result.head()

"""# Upload Result to Google Sheets

"""

from gspread_dataframe import set_with_dataframe
import gspread
from google.auth import default

# authenticate with google sheets
creds, _ = default()
gc = gspread.authorize(creds)

# create spreadsheet
title = 'DS In Context Presentation'
sh = gc.create(title=title)

# open spreadsheet and add data to it
worksheet = gc.open(title=title).sheet1
set_with_dataframe(worksheet, result)

"""# Upload Results to Google Cloud Storage

It's very simple to upload your results to Google Cloud Storage, but you have to pay :) 
"""

# df.to_csv('gs://bucket/path')